# Generated by Django 5.2.1 on 2025-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_tasks_task_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
